### ISSUE TITLE
Some Landing Pages Broken in Dev/Staging: Invalid Schema.org Markup

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/seo#35]
## Problem

Some landing pages in our staging and development environments are breaking due to malformed Schema.org markup embedded in the header element. This results in formatting issues on the web pages.

This issue arises when unregistered mock DOIs are passed to the `generate_citation_from_doi` function within the `utilities` module of the `soso` package. A detailed explanation of the root cause is available in this related issue: https://github.com/clnsmth/soso/issues/211

## Impact

This problem is currently limited to the staging and development environments. Production is not affected because it utilizes valid, registered DOIs from DataCite.

## Solution

A fix will be implemented within the `soso` package. Once the fix is available, we can resolve this issue by installing the updated version of `soso` in `seo`.

**Comment by servilla** [comment]
@clnsmth These `unregistered mock DOIs` are registered with DataCite using DataCite's test DOI prefix. SOSO appears somewhat brittle because of assumptions about operating within a perfect world (e.g., test DOIs, integration with test environments, etc.). SOSO must be more flexible and work within non-ideal environments (see this comment https://github.com/clnsmth/soso/issues/211#issuecomment-2395172061).

**Comment by clnsmth** [comment]
Hi @servilla,

Regarding citation formats for `soso`, we can use any style you prefer.

For the EDI production, staging, and development tiers, would you like to use the default format returned by the [cite](https://github.com/PASTAplus/cite) service (i.e. ESIP format)?

Let me know your thoughts. Thanks!

**Comment by clnsmth** [comment]
@servilla and I discussed this issue and agreed that the best approach is to leverage the [PASTAplus/cite](https://github.com/PASTAplus/cite) service to generate citations in the ESIP format for the Scheme.org markup implemented in the development, staging, and production environments.

This citation will be added to the `schema_org` module of `seo` at line 180: https://github.com/PASTAplus/seo/blob/ff85f6d471bc4e47009a5ee315396787a90973e3/webapp/schema_org.py#L180

This ensures the citation formatting in the Schema.org markup matches the citation formatting on the data portal landing pages.
